### ISSUE TITLE
Create docker images and build scripts for project deployment

### ISSUE THREAD

**Issue by poorva1209** [GRIDAPPSD/GridAPPS-D#29]
- Create docker images for FNCS, GridLAB-D, Viz(node.js), GOSS, GridAPPS-D and Blazegraph.
- Deploy docker images on production, test and distribution VM
- Share docker images with External ADMS team.
- Coordinate it with Ansible or docker compose.
- Document docker images deploy instruction on readthedocs for fresh deployment.

acceptance criteria: 
- [ ] Docker images exist on DockerHub
- [ ] Ansible Script exist on repositories
- [ ] Docker image deployed on fresh VM by an internal team member by following readthedocs instructions.
- [ ] Docker images deployed on test and production VMs

**Comment by craigpnnl** [comment]
I have access to do snapshots.  I have been asked not to do it daily.

**Comment by poorva1209** [comment]
@craig8 Update acceptance criteria is needed.

**Comment by poorva1209** [comment]
Issue moved to [GRIDAPPSD/GOSS-GridAPPS-D #329](https://github.com/GRIDAPPSD/GOSS-GridAPPS-D/issues/329) via [**ZenHub**](https://www.zenhub.com/)
