### ISSUE TITLE
Labels aren't showing up in the viz application in the docker container

### ISSUE THREAD

**Issue by craigpnnl** [GRIDAPPSD/GridAPPS-D#49]
@craig8 is going to look into this to figure out if this is a docker thing or a viz project thing @bibiraju

**Comment by bibiraju** [comment]
Do you mean the voltage values and the regulator labels?

**Comment by craigpnnl** [comment]
yes

**Comment by poorva1209** [comment]
Issue moved to [GRIDAPPSD/GOSS-GridAPPS-D #326](https://github.com/GRIDAPPSD/GOSS-GridAPPS-D/issues/326) via [**ZenHub**](https://www.zenhub.com/)
