### ISSUE TITLE
Add documentation for how to run the default gridappsd simulation via docker to readthedocs.

### ISSUE THREAD

**Issue by craigpnnl** [GRIDAPPSD/GridAPPS-D#50]

**Comment by poorva1209** [comment]
Issue moved to [GRIDAPPSD/GOSS-GridAPPS-D #316](https://github.com/GRIDAPPSD/GOSS-GridAPPS-D/issues/316) via [**ZenHub**](https://www.zenhub.com/)

**Comment by craigpnnl** [comment]
The readthedocs part of this is not done...unless you want to add a follow up just for readthedocs I would like to leave this open until Thursday (when I plan on having this done)

**Comment by poorva1209** [comment]
Issue moved to [GRIDAPPSD/GOSS-GridAPPS-D #323](https://github.com/GRIDAPPSD/GOSS-GridAPPS-D/issues/323) via [**ZenHub**](https://www.zenhub.com/)
